import streamlit as st

st.set_page_config(
    page_title="AI Trading Intelligence Platform",
    layout="wide",
    page_icon="📊"
)

# ==============================
# GLOBAL STYLING
# ==============================

st.markdown("""
<style>

body {
    background-color: #0E1117;
}

.main {
    background: linear-gradient(180deg, #0E1117 0%, #0B0F18 100%);
}

.block-container {
    padding-top: 2rem;
    padding-bottom: 4rem;
}

.hero-section {
    background-image: url("images/hero.jpg");
    background-size: cover;
    background-position: center;
    padding: 100px 60px;
    border-radius: 25px;
    position: relative;
    margin-bottom: 80px;
}

.hero-overlay {
    background: rgba(14,17,23,0.85);
    padding: 40px;
    border-radius: 20px;
}

.hero-title {
    font-size: 56px;
    font-weight: 800;
    color: #00FFA3;
}

.hero-text {
    font-size: 18px;
    line-height: 1.8;
    color: #C5C6C7;
    margin-top: 20px;
}

.section-title {
    font-size: 36px;
    font-weight: 700;
    color: #00FFA3;
    margin-bottom: 20px;
}

.section-text {
    font-size: 17px;
    line-height: 1.8;
    color: #C5C6C7;
}

.feature-box {
    padding: 40px;
    background-color: #141A2A;
    border-radius: 20px;
}

.cta-box {
    background: linear-gradient(135deg, #00FFA3, #00C896);
    padding: 60px;
    border-radius: 25px;
    text-align: center;
    color: black;
    margin-top: 80px;
}

</style>
""", unsafe_allow_html=True)

# ==============================
# HERO SECTION
# ==============================

st.markdown("""
<div class="hero-section">
    <div class="hero-overlay">
        <div class="hero-title">AI Trading Intelligence Platform</div>
        <div class="hero-text">
            A quantitative research system engineered to transform complex 
            financial market data into structured, machine-driven trading intelligence.
            <br><br>
            By integrating predictive modeling, risk-adjusted validation, and 
            systematic performance analytics, the platform enables disciplined 
            decision-making rooted in probability rather than emotion.
        </div>
    </div>
</div>
""", unsafe_allow_html=True)

# ==============================
# ABOUT SECTION
# ==============================

st.markdown('<div class="section-title">Our Quantitative Methodology</div>', unsafe_allow_html=True)

st.markdown("""
<div class="section-text">
The AI Trading Intelligence Platform is built upon institutional-grade research principles.

Market data is collected and transformed into predictive indicators, processed through 
machine learning classification models, and validated using structured backtesting workflows. 
Performance is evaluated through risk-adjusted metrics rather than raw returns alone.

This ensures that every signal generated by the system is assessed within a 
disciplined analytical framework.
</div>
""", unsafe_allow_html=True)

st.divider()

# ==============================
# FEATURE 1 – Prediction
# ==============================

col1, col2 = st.columns([1,1])

with col1:
    st.image("images/prediction.jpg", use_container_width=True)

with col2:
    st.markdown("""
    <div class="feature-box">
        <div class="section-title">AI Prediction Engine</div>
        <div class="section-text">
        The Prediction Engine leverages supervised machine learning algorithms 
        to evaluate historical price structures and generate directional signals.

        Each BUY or SELL output is accompanied by a confidence measure, 
        allowing traders to interpret results within a probabilistic context.

        The goal is structured insight — not speculation.
        </div>
    </div>
    """, unsafe_allow_html=True)

st.divider()

# ==============================
# FEATURE 2 – Backtesting
# ==============================

col1, col2 = st.columns([1,1])

with col1:
    st.markdown("""
    <div class="feature-box">
        <div class="section-title">Strategy Backtesting Laboratory</div>
        <div class="section-text">
        Before deployment, every predictive logic must withstand 
        historical validation.

        This module compares AI-driven performance against traditional 
        Buy & Hold strategies, generating equity curves and 
        structural return analytics to evaluate sustainability.
        </div>
    </div>
    """, unsafe_allow_html=True)

with col2:
    st.image("images/backtest.jpg", use_container_width=True)

st.divider()

# ==============================
# CALL TO ACTION
# ==============================

st.markdown("""
<div class="cta-box">
    <h2>Begin Your Quantitative Trading Analysis</h2>
    <p>Explore predictive modeling, historical validation, and institutional-grade risk analytics.</p>
</div>
""", unsafe_allow_html=True)
